SELECT CONCAT(Name,'(',LEFT(OCCUPATION,1),')')
FROM OCCUPATIONS
ORDER BY Name,LEFT(OCCUPATION,1); 
SELECT CONCAT('There are a total of ',COUNT(OCCUPATION),' ',LOWER(OCCUPATION),'s.')
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION),OCCUPATION;